# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
