# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_auto_20161105_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='precipProb',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='field',
            name='envHumidity',
            field=models.DecimalField(decimal_places=3, default=0.83, max_digits=10),
        ),
        migrations.AlterField(
            model_name='field',
            name='envTemp',
            field=models.DecimalField(decimal_places=3, default=5.144444444444443, max_digits=10),
        ),
        migrations.AlterField(
            model_name='field',
            name='light',
            field=models.CharField(default='dark', max_length=20),
        ),
    ]
